apiVersion: v2
type: application
appVersion: latest
description: A Matrix-Signal puppeting bridge.
name: mautrix-signal
version: 0.0.5
keywords:
  - synapse
  - chat
  - matrix
  - signal
home: https://github.com/tulir/mautrix-signal
sources:
  - https://github.com/matrix-org/synapse
maintainers:
  - name: Gavin Mogan
    email: helm@gavinmogan.com
annotations:
  artifacthub.io/changes: |
    - Store uploaded files in a directory both services can access it
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/images: |
    - name: mautrix-signal
      image: dock.mau.dev/tulir/mautrix-signal:latest
    - name: signald
      image: finn/signald:0-13-0
