apiVersion: v2
type: application
appVersion: latest
description: A Matrix-Signal puppeting bridge.
name: mautrix-signal
version: 0.0.3
keywords:
  - synapse
  - chat
  - matrix
  - signal
home: https://github.com/tulir/mautrix-signal
sources:
  - https://github.com/matrix-org/synapse
maintainers:
  - name: Gavin Mogan
    email: helm@gavinmogan.com
annotations:
  artifacthub.io/changes: |
    - This is what changed in this version
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/images: |
    - name: nginx
      image: nginx:2.4.2
