apiVersion: v2
type: application
appVersion: latest
description: A Matrix-Signal puppeting bridge.
name: mautrix-signal
version: 0.0.7
keywords:
  - synapse
  - chat
  - matrix
  - signal
home: https://github.com/tulir/mautrix-signal
sources:
  - https://github.com/matrix-org/synapse
maintainers:
  - name: Gavin Mogan
    email: helm@gavinmogan.com
annotations:
  artifacthub.io/changes: |
    - "Migrate to new signald app/image"
    - "Enable signald's metrics"
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/images: |
    - name: mautrix-signal
      image: dock.mau.dev/mautrix/signal:latest
    - name: signald
      image: signald/signald:amd64-4d18e1e3a816e98a304f522ae393cde565638273
