apiVersion: v2
type: application
appVersion: latest
description: A Matrix-Signal puppeting bridge.
name: mautrix-signal
version: 0.0.8
keywords:
  - synapse
  - chat
  - matrix
  - signal
home: https://github.com/tulir/mautrix-signal
sources:
  - https://github.com/matrix-org/synapse
maintainers:
  - name: Gavin Mogan
    email: helm@gavinmogan.com
annotations:
  artifacthub.io/changes: |
    - "Latest signald (which should fix log4shell)"
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/images: |
    - name: mautrix-signal
      image: dock.mau.dev/mautrix/signal:latest
    - name: signald
      image: signald/signald:amd64-7354fec1d4233224e6827869f64d95ea06981205
